// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkFq4cp7X20SKFX5n_vea1UjvILZehuyE',
    appId: '1:169769415585:web:83f3d45c75f868cbe951e0',
    messagingSenderId: '169769415585',
    projectId: 'p1flutterai',
    authDomain: 'p1flutterai.firebaseapp.com',
    storageBucket: 'p1flutterai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsRfeci5b5nwD2wrrN2vNvMB7siOb8Q0k',
    appId: '1:169769415585:android:d29626dd77d28ff1e951e0',
    messagingSenderId: '169769415585',
    projectId: 'p1flutterai',
    storageBucket: 'p1flutterai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy6ijYPPnJqb0njmpgnqYGPa8Ad9onWSY',
    appId: '1:169769415585:ios:f4a64f24d3425d77e951e0',
    messagingSenderId: '169769415585',
    projectId: 'p1flutterai',
    storageBucket: 'p1flutterai.appspot.com',
    iosClientId: '169769415585-poad9pfg6hu6403oudscd22ccb1f972d.apps.googleusercontent.com',
    iosBundleId: 'com.flutterai.p1FlutterAi',
  );
}
